name: Publish Docker image
on:
  release:
    types: [published]
# using env instead of hard code
env:
  DOCKER_HUB_REPO: badkins96/p4repo
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          username: badkins96
          password: bBproject4
          repository: ${{ env.DOCKER_HUB_REPO }}
          tag_with_ref: true
